aws/aws-northstar

- examples/create-react-app/package.json
- examples/create-react-app/tsconfig.json
Update the dependencies of example
> chore: Update the example dependencies

- src/layouts/AppLayout/AppLayout.md
- src/layouts/AppLayout/index.stories.tsx
- src/layouts/AppLayout/index.tsx
General refinement of language
> chore: content clean up

- README.md
- docs/GettingStarted.md
- package.json
> docs: Add the badges

- src/components/Card/index.stories.tsx
- src/components/Card/index.tsx
Add onMouseEnter, onMouseMove, and onMouseOut events for the card
> fix(Card): Add mouse events to the card

- src/layouts/Box/index.tsx
> fix(Box): Typo

- .releaserc
This PR is to override the preset rule to:
* create patch release for feat type. 
* Create patch release for README scope so that the README file in the NPM package can be updated. 
* Create patch release for style type. 
> build: Add custom release rules

- src/components/Button/Button.md
- src/components/Button/index.stories.tsx
- src/components/Button/index.test.tsx
- src/components/Button/index.tsx
N/A
Add in new prop `size` to the `Button` component
> feat(button): add size prop to button component

- src/components/index.ts
> fix(TimePicker): export timepicker component

- package.json
- scripts/build.sh
- tsconfig.build.esm.json
#38 
Build esm package so that users can use es modules if they prefer. 
> build: Create esm package. Closes #38

- src/components/FileUpload/FileUpload.md
- src/components/FileUpload/components/FileTokenLabel/index.test.tsx
- src/components/FileUpload/components/FileTokenLabel/index.tsx
- src/components/FileUpload/index.stories.tsx
- src/components/FileUpload/index.test.tsx
- src/components/FileUpload/index.tsx
- src/components/FileUpload/types.ts
- src/components/FormField/index.test.tsx
- src/components/FormField/index.tsx
- src/components/FormRenderer/FormRenderer.md
- src/components/FormRenderer/components/Custom/index.tsx
- src/components/FormRenderer/index.stories.tsx
- src/components/FormRenderer/index.test.tsx
- src/components/FormRenderer/index.tsx
- src/components/Multiselect/index.tsx
- src/components/TokenGroup/TokenGroup.md
- src/components/TokenGroup/components/Token/index.tsx
- src/components/TokenGroup/index.test.tsx
- src/components/TokenGroup/index.tsx
- src/layouts/Inline/index.tsx
- src/layouts/Stack/index.tsx
#52 
* Add FileUpload component
* Add footer to the FormField so the file list can be positioned below the hint text
* Add FormRenderer Custom component support so that users can use FileUpload as FormRenderer Custom component
> Feat: FileUpload component 

- src/components/HelpPanel/index.tsx
Closes #62 
Add missing useMemo styles deps that cause style corruption. 
> fix(HelpPanel): Add missing useMemo styles deps that causes style corruption

- .github/dependabot.yml
Add dependabot to manage dependencies
> build: Create dependabot to update dependencies

- src/components/Popover/Popover.md
- src/components/Popover/index.stories.tsx
- src/components/Popover/index.test.tsx
- src/components/Popover/index.tsx
- src/components/index.ts
- src/hooks/useUniqueId/index.test.tsx
- src/hooks/useUniqueId/index.tsx
*Issue #, if available:* https://github.com/aws/aws-northstar/issues/66
*Description of changes:* Added a Popover component that can be used to display some content on top of another.
> feat: Add Popover component

- src/layouts/GetStarted/index.test.tsx
Add a test case for GetStarted layout component. 
> test(GetStarted): Add test case

- src/components/Input/index.test.tsx
- src/components/Input/index.tsx
Adds optional onBlur and onFocus methods to the `Input` component.
> feat(Input): Add onBlur and onFocus to Input

- package-lock.json
Bump the versions of elliptic and ini to address the security warning
> build(deps-dev): Bump elliptic and ini

- src/components/ProgressBar/ProgressBar.md
- src/components/ProgressBar/index.stories.tsx
- src/components/ProgressBar/index.test.tsx
- src/components/ProgressBar/index.tsx
Add support for a Circular Progress Bar.
> feat: Add support for circular progress bar

- src/components/ProgressBar/index.stories.tsx
- src/components/ProgressBar/index.tsx
Add support to pass native properties to ProgressBar.
> fix: Add support to pass properties into ProgressBar

- src/layouts/AppLayout/AppLayout.md
- src/layouts/AppLayout/index.stories.tsx
- src/layouts/AppLayout/index.test.tsx
- src/layouts/AppLayout/index.tsx
Add support for dynamic help panel content
> feat: Add support for dynamic help panel content

- src/layouts/Container/index.test.tsx
- src/layouts/Container/index.tsx
Adding support for ReactNode in the subtitle of the Container.
> feat: Add support for arbitrary react in Container subtitle

- package-lock.json
- package.json
- src/components/Textarea/Textarea.md
- src/components/Textarea/index.stories.tsx
- src/components/Textarea/index.test.tsx
- src/components/Textarea/index.tsx
Add support for classes, onKeyUp and onKeyDown to Textarea
> feat: Add support for classes, onKeyUp and onKeyDown to Textarea

- src/components/FormRenderer/components/FieldArray/components/FieldArrayItem/index.tsx
- src/components/FormRenderer/components/FieldArray/index.tsx
- src/components/FormRenderer/index.test.tsx
Support grid layout for FieldArrayItem
> feat: Support grid layout for FieldArrayItem

- scripts/postRelease.sh
> build: fix postRelease.sh script

- src/layouts/Inline/index.test.tsx
- src/layouts/Inline/index.tsx
filter null values from Inline children
> feat: filter null values from Inline children

- src/components/TokenGroup/components/Token/index.tsx
make onDismiss optional for Token
> feat: make onDismiss optional for Token

- package.json
- yarn.lock
Bump trim from 0.0.1 to 0.0.3 using selective dependency resolution to address security warning. 
> build(deps-dev): Bump trim from 0.0.1 to 0.0.3

- src/themes/default.ts
#199 
Remove hover outline for disabled input elements
> fix(Input): Remove hover outline for disabled input elements. Closes #199

- jest.config.js
- src/advanced/NotificationButton/index.tsx
- src/components/ButtonDropdown/index.tsx
- src/components/ExpandableSection/index.tsx
- src/components/FormField/index.tsx
- src/components/Table/components/SettingsBar/index.tsx
- src/components/Table/components/SettingsPopover/index.tsx
- src/components/Table/index.tsx
- src/components/Wizard/components/StepNavigation/index.tsx
Some style fixes:
**FormField**:
**before:**
**after:**
**Table**:
**before:**
**after:**
> fix(FormField): Align the components vertically

- .eslintrc.json
- docs/components/ColorTable/index.tsx
- docs/components/DefaultTypeStyle/index.tsx
- docs/components/GeneralGuidelines/index.tsx
- docs/components/WritingGuidelines/index.tsx
- src/charts/utils/getFillColor/index.ts
- src/charts/utils/getStrokeColor/index.ts
- src/components/Button/components/ButtonIcon/index.tsx
- src/components/Icon/index.tsx
- src/components/Placeholder/index.tsx
- src/components/Table/components/ContainerHeaderContent/index.tsx
- src/components/Table/components/SettingsPopover/index.tsx
- src/components/Table/data/groupBy.ts
- src/components/Table/data/long.ts
- src/components/Table/data/short.ts
- src/components/Table/index.tsx
- src/config/spacingMapping.tsx
- src/layouts/ColumnLayout/components/Column/index.tsx
Fix new eslint warnings from the new version of *eslint-config-react-app* and override the rules to exclude storybook files. 
> refactor: Fix the eslint warnings

- package.json
- src/components/Autosuggest/index.test.tsx
- src/components/Autosuggest/index.tsx
- src/components/Table/index.tsx
Match the preselected value in the options
> fix: Autosuggest preselected value match

- package.json
- src/components/MarkdownViewer/MarkdownViewer.md
- src/components/MarkdownViewer/index.test.tsx
- src/components/MarkdownViewer/index.tsx
- yarn.lock
Test and clean up code based on PR #220 
> feat: Bump react-markdown version from 5.0.3 to 6.0.2

- src/components/Table/components/BaseColumns/index.tsx
- src/components/Table/components/ColumnsGrouping/index.tsx
- src/components/Table/components/ColumnsSelector/index.tsx
- src/components/Table/index.tsx
> refactor: Table components

- src/charts/LineChart/index.tsx
- src/components/FormRenderer/FormRenderer.md
> fix(LineChart): Add the data back to the props

- src/components/FormRenderer/index.stories.tsx
- src/components/FormRenderer/index.tsx
Add support for custom validator mapping in FormRenderer
> feat: Add support for custom validator mapping in FormRenderer

- yarn.lock
> build(deps-dev): bump refractor from 3.3.1 to 3.4.0

- docs/GettingStarted.md
- src/components/Table/Table.md
> docs: Fix the table example

- src/components/FormRenderer/components/FormTemplate/index.tsx
- src/components/FormRenderer/index.stories.tsx
- src/components/FormRenderer/index.test.tsx
- src/components/FormRenderer/types.ts
- src/components/Wizard/components/WizardInner/index.tsx
> feat(FormRenderer): Add Reset Button support to non-Wizard Form

- src/components/Table/components/DefaultColumnFilter/index.tsx
- src/components/Table/components/TableHead/index.tsx
- src/components/Table/data/filterColumnDefinitions.tsx
- src/components/Table/data/groupBy.ts
- src/components/Table/data/long.ts
- src/components/Table/data/short.ts
- src/components/Table/index.stories.tsx
- src/components/Table/index.test.tsx
- src/components/Table/index.tsx
This PR is based on #270 to run tests and update docs.  
This feature is currently only supported on the **local** search. 
> feat(Table): Support local filters on columns

- src/components/Flashbar/index.tsx
- src/components/Flashbar/types.ts
- src/layouts/AppLayout/AppLayout.md
- src/layouts/AppLayout/index.stories.tsx
- src/layouts/AppLayout/index.test.tsx
- src/layouts/AppLayout/index.tsx
> feat(AppLayout): Support dynamically add and dismiss notifications via AppLayoutContext

- examples/create-react-app/src/components/Analytics/index.tsx
- src/components/PivotTable/PivotTable.md
- src/components/PivotTable/index.stories.tsx
> docs(PivotTable): Add docs on how to leverage code splitting to reduce build bundle size on large third party dependencies

- src/advanced/DeleteConfirmationDialog/DeleteConfirmationDialog.md
- src/advanced/DeleteConfirmationDialog/index.stories.tsx
- src/advanced/DeleteConfirmationDialog/index.test.tsx
- src/advanced/DeleteConfirmationDialog/index.tsx
> feat(DeleteConfirmationDialog): Extend the DeleteConfirmationDialog to support different levels of friction

- src/components/FormRenderer/components/FieldArray/components/FieldArrayItem/index.tsx
- src/components/FormRenderer/components/FieldArray/index.tsx
- src/components/FormRenderer/index.stories.tsx
- src/components/FormRenderer/index.test.tsx
> feat(FormRenderer): Support FieldArray with complex layout

- package.json
- yarn.lock
> build(deps-dev): Fix the version of immer to address security alert

- src/components/Autosuggest/Autosuggest.md
- src/components/Autosuggest/index.stories.tsx
- src/components/Autosuggest/index.test.tsx
- src/components/Autosuggest/index.tsx
> chore: Remove the debug flag

- src/components/FormRenderer/components/Radio/index.tsx
- src/components/FormRenderer/index.stories.tsx
- src/components/FormRenderer/index.test.tsx
- src/components/FormRenderer/types.ts
Render radio button description in FormRenderer
**Before**
**After**
> feat(FormRenderer): Render radio button description

- src/components/Button/index.test.tsx
- src/components/Button/index.tsx
> fix(Button): Add missing aria-label to buttons without icons

- .github/dependabot.yml
> build: Disable auto rebase to reduce noisy notifications

- docs/GettingStarted.md
- examples/create-react-app/LICENSE
- examples/create-react-app/package.json
- examples/create-react-app/src/App.tsx
- examples/create-react-app/src/components/AppLayout/index.tsx
- examples/create-react-app/src/components/Dashboard/components/OrdersTable/index.tsx
- examples/create-react-app/src/components/Dashboard/components/Overview/index.tsx
- examples/create-react-app/src/components/Dashboard/components/PercentageSaleByItems/index.tsx
- examples/create-react-app/src/components/Dashboard/components/SaleByItems/index.tsx
- examples/create-react-app/src/components/Dashboard/components/SaleByMonths/index.tsx
- examples/create-react-app/src/components/Dashboard/index.tsx
- examples/create-react-app/src/components/OrderForm/index.tsx
- src/components/PivotTable/PivotTable.md
#419 
Update the example app and docs
> docs: Update example deps versions. Closes #419

- package.json
- yarn.lock
> build(deps-dev): Force resolution versions of deps to address security warning

- .eslintrc.json
- package.json
- src/advanced/JupyterNotebook/JupyterNotebook.md
- src/advanced/JupyterNotebook/index.tsx
- yarn.lock
Update the doc for Jupyter Notebook so that the doc is rendered correctly. 
> docs: Update docs for Jupyter Notebook Viewer

- .github/dependabot.yml
> build: Exclude react-markdown from dependabot

- .github/dependabot.yml
> build: Add new dependabot ignore

- yarn.lock
> build: Upgrade prismjs to address security warning

- src/components/SideNavigation/index.stories.tsx
- src/components/SideNavigation/index.test.tsx
- src/components/SideNavigation/index.tsx
> feat(SideNavigation): Add defaultExpandedAll flag to allow expanding all sections by default

- examples/create-react-app/package.json
> docs: Fix the code example react 18 issue

- README.md
- README_NPM_PACKAGE.md
- docs/AboutNorthStar.md
> docs: Add docs to introduce Cloudscape

- packages/legacy/package.json
> build: Fix release package

- packages/legacy/docs/GettingStarted.md
- scripts/build.sh
> docs: Update sample app

- package.json
- packages/legacy/package.json
- yarn.lock
> build(deps-dev): Force resolution trim-newlines version to address security finding

- package.json
- yarn.lock
> build(deps-dev): Bump the version of webpack and fix version of chalk

- README.md
- package.json
- packages/ui/docs/Introduction.stories.mdx
- yarn.lock
> docs: Update NorthStar v2 documentation website page 

- patches/@semantic-release+npm+8.0.3.patch
> build: Add patch file to @semantic-release/npm to support npm publish build folder for workspace 

- packages/legacy/src/components/Table/components/SettingsBar/index.test.tsx
- packages/legacy/src/components/Table/components/SettingsBar/index.tsx
- packages/legacy/src/components/Table/index.tsx
> fix: Fix an issue where the pagination is not displayed correctly when there is 0 rows filtered out. Closes #714

- packages/examples/legacy/tsconfig.json
- packages/legacy/README.md
> docs: Add maintenance notes to NorthStar legacy

- README.md
- packages/legacy/README.md
- packages/legacy/docs/AboutNorthStar.md
> feat: Update readme for Northstar legacy

- packages/ui/src/components/AppLayout/index.stories.tsx
- packages/ui/src/components/AppLayout/index.tsx
- packages/ui/src/components/AppLayout/utils/getBreadcrumbs/index.test.ts
- packages/ui/src/components/AppLayout/utils/getBreadcrumbs/index.ts
- packages/ui/src/components/CognitoAuth/context.ts
This PR is to fix the issues related to the automatically generated breadcrumb group: 
* The breadcrumb group and active href of side navigation was not updated when the users click the links outside of side navigation or breadcrumbs
* The breadcrumb href is not generated properly when the defaultBreadcrumb is not a */*
* The breadcrumb href is not generated properly if there is search string present
> fix(AppLayout): Fix the issue where the automatically generated breadcrumbs was not generated properly

- package.json
- packages/ui/src/components/AppLayout/components/NavHeader/index.tsx
- packages/ui/src/components/AppLayout/index.stories.tsx
- packages/ui/src/components/AppLayout/index.tsx
- scripts/build.sh
- yarn.lock
> fix(AppLayout): Listen to notifications top down update

- packages/ui/src/components/FormRenderer/components/FieldArray/index.tsx
> fix(FormRenderer): Fix an issue where FieldArray was not showing validation errors when used inside a Wizard

- packages/ui/package.json
- yarn.lock
> fix(FormRenderer): Bump the version of data driven forms to address n issue related to conditional form components validation in Wizard. Close #910

- package.json
- yarn.lock
> build(deps-dev): Bump and fix postcss version

- yarn.lock
> build(deps): Bump ws from 8.13.0 to 8.17.1

- package.json
- yarn.lock
> build(deps-dev): Fix the version of braces to ^3.0.3

- package.json
- yarn.lock
> build(deps-dev): Bump version of deps

- yarn.lock
> build(deps-build): Bump version of cross-spawn

- packages/ui/src/components/FormRenderer/index.tsx
- packages/ui/src/components/FormRenderer/stories/ActionMapper.stories.tsx
> feat(FormRenderer): Expand FormRenderer props (Close #1070)
