aws/aws-northstar

.travis.yml, package.json, scripts/build.sh
This PR is to preinstall the git secrets and typescript to fix the Travis CI build
=> build: Install the git secrets so that the Travis build can pass

src/components/BreadcrumbGroup/index.test.tsx, src/components/BreadcrumbGroup/index.tsx
#27 
Preserve the casing of generated links in the BreadcrumbGroup.
=> fix(BreadcrumbGroup): Preserve casing of generated links. Fixes #27

src/components/Form/Form.md
*Issue
[FormFieldProps.ControlId is required](https://github.com/aws/aws-northstar/blob/a7a37094fd9173bfba580282fa9eabbe54fb9359/src/components/FormField/index.tsx#L58), but not in the documentation code.
I get the following error when I copy the code:
Add Form Field
=> docs: add FormField.ControllId

src/layouts/AppLayout/index.tsx
In Chrome, the [default stylesheet adds an outline](https://chromium.googlesource.com/chromium/src/third_party/+/master/blink/renderer/core/html/resources/html.css#1056)
which gets applied to the main content Box. This change removes this outline.
Before:
After:
=> style(AppLayout): Remove outline style when main content in AppLayout is focussed

src/components/FormRenderer/components/Subform/index.tsx
https://github.com/aws/aws-northstar/issues/34
Pass the showError prop from Wizard to SubForm to fields inside SubForm to fix the issue where the error is not shown when validation failed in SubForm used inside Wizard
After the fix, the error will be displayed:
=> fix: Show error when validation failed in SubForm used inside Wizard

src/components/Input/Input.md, src/components/Input/index.stories.tsx, src/components/Input/index.test.tsx, src/components/Input/index.tsx
The `Input` component uses the props `autocomplete` and  `disableBrowserAutocorrect ` wrongly, this PR swap them to allow client to set them accordingly.
Additionally, the `autocorrect` property is not supported by Material UI ( https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/OutlinedInput/OutlinedInput.js#L144-L286 ) thus is not set to the underlying input once rendered. `autocomplete` works as expected with this fix
=> fix(input): swap autocomplete and autocorrect property usage

src/components/Icon/Icon.md, src/components/Icon/index.stories.tsx, src/components/Icon/index.test.tsx, src/components/Icon/index.tsx, src/components/index.ts
N/A
Add in a new `Icon` component to render material ui icons: https://material-ui.com/components/material-icons/
=> feat(icon): create icon component to render material ui icons

src/components/Button/Button.md, src/components/Button/components/ButtonIcon/index.test.tsx, src/components/Button/components/ButtonIcon/index.tsx, src/components/Button/index.stories.tsx, src/components/Icon/index.tsx
N/A
as part of the #37 feature, this pull request extend the usage of the Material UI icons to the `button` component as well.
The change is backward compatible and still permit to define the button icons with the alias defined in the component as long as extend it to allow to introduce any Material UI icon as icon name
=> feat(button): extend usage of Material UI icons to button component

.eslintrc.json, .storybook/Decorator.js, .storybook/main.js, .storybook/preview.js, package-lock.json, package.json, webpack.config.js
None
The codebase already uses `prettier`, but its rulesets are not enforced by the linting scripts (through `eslint`).
Because of this, the code styling is not checked and/or corrected according to the configured `prettier` rules as part of lints, and are missed during `husky` pre-commit checks (for example).
This change adds in `eslint` configurations that check and enforce `prettier` rules when linting, and therefore also comb + fix the codebase when `husky` / linting checks are run.
Additionally, this change also fixes files that were already failing `prettier` checks, but just weren't visible before.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> Adds prettier rules enforcement through the code linting pipeline

package.json
*Issue #, if available:* None
Currently, lints and tests run on every **commit**. 
Not only is this redundant and somewhat overly eager, but it also contributes to significant contributor friction during development. 
As the code base stands on my machine, unit tests run upwards of `~30s` for 241 tests / 32 suites --- pending optimization of tests, this is expected to grow. This means that on every commit, there is a significant break until work can be resumed.
It is arguably better to have testing performed, instead, on every **push**. Since the repository operates on a PR model, it is enough of a guarantee to have the tests pass on the push, since the push is guaranteed to occur prior to the PR.
**If proactive testing is desired**, the code base already …
=> QoL improvement: move automatic testing from pre-commit to pre-push

src/components/Autosuggest/Autosuggest.md, src/components/Autosuggest/index.stories.tsx, src/components/Autosuggest/index.test.tsx, src/components/Autosuggest/index.tsx
N/A
This PR includes the following changes for the `Autosuggest` component:
1. Include option to either remove or customise the Icon by providing a value to the `icon` prop (see image):
1.a: when `icon` prop is not defined, the default Icon will be used (search)
1.b: when  `icon` prop is provided with `false` value, the icon will be removed
2.c: when `icon` prop is one of the allowed Material Icon value  ( https://material-ui.com/components/material-icons/ ) will display it accordingly
2. Expose props `freeSolo` and `disableClearable` to allow the user to define a custom value instead of one of the provided option (eg. use-case such as search autocomplete where the user can either pick a value already available in the dropdown or input a …
=> feat/autosuggest: add in option to define custom icon and custom input

src/components/Multiselect/Multiselect.md, src/components/Multiselect/index.stories.tsx, src/components/Multiselect/index.tsx
see #44 
Use `getOptionSelected` to fix bug described here; #44 
as per Material UI docs:
```js
/**
* The value of the autocomplete.
*
* The value must have reference equality with the option in order to be selected.
* You can customize the equality behavior with the `getOptionSelected` prop.
*/
value?: T[];
```
Solved assuming that two items are equal in case their respective value is equal (`getOptionSelected={(opt, v) => opt.value === v.value}` 
Could be fixed differently by selecting the item reference from `flattenOptions` in case the above premise is not totally right
=> fix(Multiselect): fix wrong behaviour on initial value

src/components/Card/Card.md, src/components/Card/index.stories.tsx, src/components/Card/index.test.tsx, src/components/Card/index.tsx
N/A
Expose the property `titleTypographyProps` available in Material Ui to allow the consumer to define custom title style for `Card` component
eg:
=> feat(card): Allow Card component to define custom typography for the title

jest.config.js, jest/jest.globalsetup.js, src/components/FormRenderer/FormRenderer.md, src/components/FormRenderer/components/TimePicker/index.tsx, src/components/FormRenderer/index.stories.tsx, src/components/FormRenderer/index.test.tsx, src/components/FormRenderer/index.tsx, src/components/TimePicker/TimePicker.md, src/components/TimePicker/index.stories.tsx, src/components/TimePicker/index.test.tsx, src/components/TimePicker/index.tsx
Add a TimePicker component which wraps Material UI's KeyboardTimePicker.
Integrate with FormRenderer for the `time-picker` component type (`componentTypes.TIME_PICKER`).
Times are represented as `Date` objects when using the TimePicker component directly.
In FormRenderer, times are represented as ISO 8601 strings for simpler payloads sent to services.
`npm run test`
Inspected storybook and styleguide.
=> feat: TimePicker

src/components/FormRenderer/components/ExpandableSection/index.tsx, src/components/FormRenderer/index.stories.tsx
Closes #49
Render controls inside ExpandableSection in FormRendered Form in a Stack. 
=> fix: ExpandableSection in FormRenderer renders form fields inline - Closes #49

src/layouts/AppLayout/AppLayout.md, src/layouts/AppLayout/constants.ts, src/layouts/AppLayout/index.stories.tsx, src/layouts/AppLayout/index.test.tsx, src/layouts/AppLayout/index.tsx
#57 
Add AppLayoutContext to support descendent component to trigger open/close help panel. 
=> feat: Support programmatically open help panel (Closes #57)

src/components/FileUpload/index.tsx, src/layouts/AppLayout/index.stories.tsx, src/layouts/AppLayout/index.tsx
Closes #39 
Add a new prop for AppLayout so that users can set the height of header if a custom header is used.  
=> feat(AppLayout): Allow set the height of header for custom header

src/components/RadioGroup/index.tsx
#60
*Description of changes:* 
Fixes the radio button dot alignment in Safari.
Before:
After:
=> fix(RadioGroup): Centre radio button dots in Safari, fixes #60

.github/dependabot.yml
Add react libraries into Dependabot ignore list so that we can support maximum backward compatibilities.
=> build: Add react libraries (peer-deps) into dependabot ignore list

src/components/Popover/index.stories.tsx, src/components/Popover/index.test.tsx, src/components/Popover/index.tsx
Adds an `onChange` callback for users so we can know when the popover was opened and closed, eg to fetch data to display in the popover.
=> feat(Popover): Add onChange callback

src/components/Tabs/index.test.tsx, src/components/Tabs/index.tsx
Add support for arbitrary content within a tab label.
=> feat: Add support for arbitrary tab labels

src/components/Input/index.test.tsx, src/components/Input/index.tsx
If you set the initial value of an input box to `0`, it rendered as an empty string instead!
=> fix(Input): Fix rendering of falsy values

src/components/FormRenderer/FormRenderer.md, src/components/FormRenderer/components/FormTemplate/index.tsx, src/components/FormRenderer/index.stories.tsx, src/components/FormRenderer/index.test.tsx, src/components/FormRenderer/index.tsx
Add an optional `isSubmitting` prop to `FormRenderer` which adds a loading spinner to the submit
button and disables the cancel button. This gives users visible feedback that the data they have
entered is being submitted.
=> feat(FormRenderer): Add isSubmitting boolean to improve form submit UX

.travis.yml, package.json, scripts/build.sh, yarn.lock
Move the oss-attribution-generator out of the dev-deps to suppress the security vulnerability alert. Instead, install it as global dep. 
=> build: Move the oss-attribution-generator out of deps

src/components/Popover/Popover.md, src/components/Popover/index.stories.tsx, src/components/Popover/index.test.tsx, src/components/Popover/index.tsx
Add a new `variant` prop to the Popover:
* `click` (default) the existing behaviour where the popover is opened by clicking on the trigger region
* `hover` the popover is opened by hovering the mouse over the trigger region
=> feat(Popover): Add 'hover' variant to open the popover when hovering trigger region

src/components/Multiselect/Multiselect.md, src/components/Multiselect/index.stories.tsx, src/components/Multiselect/index.test.tsx, src/components/Multiselect/index.tsx
Adds a `freeSolo` option to the `Multiselect` component to match the `Autosuggest` component.
For backwards compatibility, the `onChange` callback is still called with a `SelectOption[]`, and we set the `label` and `value` to the free text entered by the user.
=> feat(Multiselect): Add freeSolo for custom text in multiselect

src/components/ProgressBar/ProgressBar.md, src/components/ProgressBar/index.tsx
Circular progress bars randomly get styled purple by mui, as both the northstar and mui styles have the same precedence (just specified as a style on a class). Address this with `!important` on the northstar colour property.
=> fix(ProgressBar): fix bug with progress bar colour being overridden by mui style

.releaserc, src/advanced/NotificationButton/index.tsx, src/components/Alert/Alert.md, src/components/Alert/index.stories.tsx, src/components/Alert/index.test.tsx, src/components/Alert/index.tsx
#181
Rename the props of Alert:
- dismissable to dismissible
- dissmissLabel to dismissAriaLabel
- visable to visible
Also add the release rule to release as a minor version when the commit message includes RENAME Props 
=> refactor(Alert): RENAME Props. Closes #181

src/components/ProgressBar/index.tsx
This gets rid of the warning message printed in the chrome console:
```
Warning: Failed prop type: Material-UI: `variant="static"` was deprecated. Use `variant="determinate"` instead.
```
=> fix(ProgressBar): Don't use deprecated prop for CircularProgress

src/components/SideNavigation/index.tsx
This makes the UX consistent with ExpandableSection, ie goes from this:
```
v My collapsed heading
^ My expanded heading
item1
item2
```
to this:
```
> My collapsed heading
v My expanded heading
item1
item2
```
=> feat(SideNavigation): More intuitive icons for sections

src/components/Table/Table.md, src/components/Table/index.stories.tsx, src/components/Table/index.test.tsx, src/components/Table/index.tsx
This adds the ability to specify a `isItemDisabled` callback, which disables
selection for rows for which it evaluates to true
Note that we hide the "select all" checkbox when this is specified.
=> feat(Table): Disable selection for individual rows

package.json, yarn.lock
Remove the force resolution of dns-packet given that a new version 1.x has been released to address the security warning. 
=> build(deps-dev): Remove the force resolution of dns-packet

package.json, yarn.lock
To address this [CVE](https://github.com/advisories/GHSA-ww39-953v-wcq6) which are affecting dependencies of storybook and styleguidist, force the version of glob-parent to 5.1.2. Local testing does not show issues. 
=> build(deps-dev): Force resolution the version of glob-parent to address CVE

src/components/Table/index.tsx
This PR is to add row id value as controlId to the select inputs for the rows. And remove the workaround for the radio button select since the issue in the react-table has been fixed. 
=> feat(Table): Add row id value as controlId to the select input

src/components/Table/index.stories.tsx, src/layouts/AppLayout/index.stories.tsx, src/layouts/AppLayout/index.tsx
There are 2 issues related to the HelpPanel Drawer
- When the HelpPanel content is set dynamically, there is extra spacing in the main content area when the drawer is close. 
-  When the draw is close, the window body overflow.
This PR addresses this two issues and updates the storybook examples to be more useful:
=> fix(AppLayout): Remove the spacing caused by the HelpPanel drawer

src/components/Table/Table.md, src/components/Table/index.stories.tsx, src/components/Table/index.tsx
Users reported that when use getRowId and onSelectChange, the onSelectChange will be triggered indefinitely. 
After triage, I found out it was because of getRowId is not used properly. So this PR is to add an example and update docs on how to use getRowId and onSelectChange. 
Another consideration is to add a temporary *selected* state, compare the temporary one with the new one, if they are the same, does not trigger the onSelectChange. However, the table is quite complicated already and so try not to add more states. 
The [React Table doc](https://react-table.tanstack.com/docs/api/useTable) also mention the *getRowId* must be **memoized**. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> docs(Table): Add examples and update docs on how to use getRowId and onSelectChange

package.json, src/components/MarkdownViewer/index.tsx, yarn.lock
Bump react-markdown
close #293 
There is incompatibility between **ref** types. I suppose that we can just skip passing `code ref` to `SyntaxHighlighter`
=> build: Bump react-markdown

src/components/FormRenderer/components/FormTemplate/index.tsx, src/components/FormRenderer/components/Wizard/components/WizardStep/index.tsx, src/components/FormRenderer/components/Wizard/index.tsx, src/components/FormRenderer/index.test.tsx, src/components/FormRenderer/index.tsx, src/components/Wizard/components/WizardInner/index.tsx
The `Wizard` component doesn't use the `FormTemplate`, and so wasn't displaying a button with a
loading spinner when `isSubmitting` was true.
We use context to track whether or not the form is submitting, which means we don't re-render the
entire form every time `isSubmitting` is changed, which means the wizard doesn't "reset" to the
first step which was a pretty horrible user experience!
=> fix(FormRenderer): Honour isSubmitting prop in Wizard

src/components/Tabs/index.stories.tsx, src/components/Tabs/index.test.tsx, src/components/Tabs/index.tsx
This PR is to allow users to disable the padding in the content area.
=> feat(Tabs): Allows disabling of padding in the content area

src/layouts/AppLayout/AppLayout.md, src/layouts/AppLayout/components/Sidebar/index.tsx, src/layouts/AppLayout/components/SplitPanel/index.test.tsx, src/layouts/AppLayout/components/SplitPanel/index.tsx, src/layouts/AppLayout/index.stories.tsx, src/layouts/AppLayout/index.test.tsx, src/layouts/AppLayout/index.tsx, src/layouts/GetStarted/index.tsx, src/layouts/Paper/index.test.tsx
This PR is to add the Split Panel support to the AppLayout so that users can display detailed info in the same page. 
=> feat(AppLayout): Add Split Panel drawer support

src/layouts/AppLayout/components/SplitPanel/index.tsx
Just made some refactoring to reduce the usage of box metrics properties.
It will reduce browser layout reflows
https://gist.github.com/paulirish/5d52fb081b3570c81e3a
=> refactor(SplitPanel): Reduce the box metrics usage to reduce browser reflow

src/components/FormRenderer/index.tsx, src/components/FormRendererTable/index.test.tsx, src/components/FormRendererTable/index.tsx, src/components/Table/components/TableBody/index.tsx, src/components/Table/components/TableHead/index.tsx, src/components/Table/constants.ts, src/components/Table/hooks/useTableColumnFilter/index.tsx, src/components/Table/index.stories.tsx, src/components/Table/index.tsx, src/components/Table/types.ts, src/components/Table/utils/converter/index.test.ts, src/components/Table/utils/converter/index.ts, src/layouts/AppLayout/index.stories.tsx, src/utils/isEqual/index.test.ts, src/utils/isEqual/index.ts
The existing event **onSelectionChange** fired by the Table is hooked to the changes of react-table **selectedFlatRows**. It is affected by both the row selection changes and the filters (either global filter or column filter) to only return the selected rows within the current applied filter. The event is fired when the filter value is changed.   
In most of scenarios, it is what users expect. However, if it is used in the form for users to select one or multiple value, the users may be confused. It will be nice that we have two events to cater for different use cases.
This PR also: 
1. Refactor the Table component to move some logic out of **index.tsx** file
2. Update the FormRendererTable component to use the new event so that it always returns what users have …
=> feat(Table): Add support of onSelectedRowIdsChange to handle the event only when the row selection changes

.releaserc, package.json, tsconfig.json
Remove the sourceMap from the built npm package given that the source code is not distributed, which causes build warnings in the consumer apps created using default create-react-app 5 settings. 
=> fix: Remove sourcemap to address the build warnings in the consumers

src/components/Tabs/index.stories.tsx, src/components/Tabs/index.test.tsx, src/components/Tabs/index.tsx, src/hooks/usePrevious/index.test.tsx, src/hooks/usePrevious/index.tsx, tsconfig.build.json, tsconfig.json
#562 
Currently, activeId in Tabs component is only used as initial default value to determine the active Tab. Dynamically change activeId will not update the active Tab. This PR is to allow the usage of dynamically set activeId while keeping the original user experiences (onChange to trigger change without binding to activeId).
=> fix(Tabs): Dynamically update activeId should update the active tab. Closes #562

yarn.lock
=> build(deps-dev): Bump eventsource from 1.0.0 to 1.0.1 to address security warning

package.json, yarn.lock
=> build(deps-dev): Bump trim-newlines from 1.0.0 to 3.0.1 to address security alert

src/components/Wizard/components/WizardInner/index.tsx, src/components/Wizard/index.test.tsx, src/components/Wizard/index.tsx
*Issue #, if available:* None
Add a new prop to allow disabling of Next/Submit button in Wizard. This is necessary to implement client-side validation and block user from moving forward until the conditions are met. 
=> feat: Be able to disable next/submit button in Wizard.

package.json, yarn.lock
=> build(deps): Upgrade recharts from 2.1.12 to 2.1.14 and force resolution the version of d3-color

packages/legacy/src/hooks/useScrollPosition/index.tsx
Hey there :) While analyzing the project I found this small issue.
The typeof is compared to undefined. This comparison is invalid because typeof always returns strings.
=> Invalid comparison

packages/ui/src/components/CognitoAuth/CognitoAuth.stories.mdx, packages/ui/src/components/CognitoAuth/context.ts, packages/ui/src/components/CognitoAuth/devStories/useSigv4Client.stories.tsx, packages/ui/src/components/CognitoAuth/hooks/useSigv4Client/index.test.tsx, packages/ui/src/components/CognitoAuth/hooks/useSigv4Client/index.tsx, packages/ui/src/components/CognitoAuth/hooks/useSigv4Client/useSigv4Client.stories.mdx, packages/ui/src/components/CognitoAuth/index.tsx
This PR is to update the useSigv4Client to be a async callback not much data needs to be kept in the state. And consumers can use *try-catch block* to handle both initialization errors or network call errors. 
This PR is also adding two utilities function into CognitoAuthContext: getAuthenticatedUserAttributes and getAuthenticatedUserSession 
=> fix(CognitoAuth-useSigv4Client): BREAKING CHANGE - Update the useSigv4Client to be a callback

packages/ui/README.md, packages/ui/docs/GettingStarted.stories.mdx, packages/ui/package.json, yarn.lock
When @cloudscape-design/components is also listed as project dependencies, 2 different versions of @cloudscape-design/components may be installed. This may cause inconsistency in AppLayout rendering. 
This PR is to move  @cloudscape-design/components out from dependencies and list it as peer dependencies. Consumer projects has to install it explicitly. For most use cases, @cloudscape-design/components is listed as project dependencies already to support usage of native Cloudscape components so it should not impact majority of users. 
This PR is also to list react-markdown as dependency and clean up peer dependencies (should not have direct user impacts)
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> fix: BREAKING CHANGE - List @cloudscape-design/components as peer dependencies

packages/ui/src/components/Table/components/FullDataTable/index.tsx, packages/ui/src/components/Table/components/Header/index.tsx, packages/ui/src/components/Table/components/RemoteUpdateTable/index.tsx, packages/ui/src/components/Table/index.stories.tsx, packages/ui/src/components/Table/types.ts
#919 
#920
This PR:
* Allow use of custom header
* Support more header props 
* Improve documentations on header props
=> feat(Table): Allow use of custom header and support more header props. Close #919 #920

packages/ui/src/components/CognitoAuth/hooks/useSigv4Client/index.tsx, packages/ui/src/components/CognitoAuth/hooks/useSigv4Client/utils/getCredentials/cache.ts, packages/ui/src/components/CognitoAuth/hooks/useSigv4Client/utils/getCredentials/index.test.ts, packages/ui/src/components/CognitoAuth/hooks/useSigv4Client/utils/getCredentials/index.ts
Previously prior to every api call, a request to cognito was sent to fetch credentials.
This change caches credentials until 30s before they expire, removing the extra calls and reducing api call latency.
=> feat(useSigv4Client): cache credentials to reduce api call latency

packages/ui/src/components/FormRenderer/components/Wizard/index.stories.tsx, packages/ui/src/components/FormRenderer/components/Wizard/index.test.tsx, packages/ui/src/components/FormRenderer/components/Wizard/index.tsx
#950 
Add onNavigating event handler support to FormRenderer Wizard so that users can hook server side validation or server side business logic when the Wizard navigation changes. 
=> feat(FormRenderer-Wizard): Support onNavigating event. Close #950

packages/ui/src/components/InfiniteQuerySelect/index.stories.tsx, packages/ui/src/components/InfiniteQuerySelect/index.test.tsx, packages/ui/src/components/InfiniteQuerySelect/index.tsx, packages/ui/src/components/InfiniteQueryTable/index.stories.tsx, packages/ui/src/components/index.ts
Like InfiniteQueryTable, this wraps the Cloudscape Select component for selecting from items which are returned from a paginated API.
Additionally fix the code examples in the storybook documentation for InfiniteQueryTable since it did not render properly.
=> feat(InfiniteQuerySelect): add infinite query select component

packages/ui/src/components/FormRenderer/components/Wizard/index.stories.tsx, packages/ui/src/components/FormRenderer/components/Wizard/index.tsx
Include values in the FormRenderer Wizard onNavigating event so the consumers can validate values in the server side or store the values
=> fix(FormRenderer): Include values in the Wizard onNavigating event

packages/ui/src/components/FormRenderer/components/Wizard/index.tsx
#991 
This PR is to fix an issue where validation can be skipped in certain scenarios, for instance, the scenarios specified in the issue #991 by using a maximum step index parameter. If the active step index is less than the maximum step index (For the scenario that the user has visited a page after the current page and navigated back), the validation will be triggered. 
=> fix(FormRenderer-Wizard): Fix an issue where validation can be skipped in certain scenarios. Close #991

packages/ui/src/components/FormRenderer/hoc/withDataDrivenFormField/index.tsx, packages/ui/src/components/FormRenderer/utils/getErrorText/index.ts
Errors returned by the `onSubmit` callback end up in the `submitError` property rather than `error`. Update the `getErrorText` method to display either if defined.
Fixes #1063 
=> fix(form-renderer): display errors returned by submit callback
